### ISSUE TITLE
'pip install pypolyagamma --user' breaks pip

### ISSUE THREAD

**Issue by kaandocal** [slinderman/pypolyagamma#19]
This is an issue I've encountered on two different computers. When installing pypolyagamma via pip (local install), the program first installs copies of numpy, scipy etc. (pypolyagamma's dependencies) collected from pypolyagamma, even if the packages are already installed and up to date. After the installation the python module pkg_resources (on which pip itself depends) stops working, leaving the python package management system in an unusable state. The traceback is as follows:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
ImportError: No module named 'pip._vendor.pkg_resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 13, in <module>
    from pip.exceptions import InstallationError, CommandError, PipError
  File "/usr/lib/python3/dist-packages/pip/exceptions.py", line 6, in <module>
    from pip._vendor.six import iteritems
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 75, in <module>
    vendored("pkg_resources")
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2927, in <module>
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2913, in _call_aside
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 956, in subscribe
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2952, in <lambda>
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2515, in activate
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2097, in declare_namespace
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2047, in _handle_ns
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

This can be fixed by erasing the local site-packages directory (as this was a local install). If I force a pip install without the dependencies, this problem does not appear and pypolyagamma works fine. The issue seems to be related to the packaging. 

This problem appears on Ubuntu MATE and Mac OS X, with Python 3.5.

**Comment by slinderman** [comment]
Thanks for raising this @kaandocal.  Some googling suggests that this is
perhaps related to your version of Python and pip/setuptools.  C.f.
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2990 I'm
running Python 3.6.3 with the latest setuptools and I was unable to
reproduce this issue.   Could you try updating?

**Comment by dranaju** [comment]
I had the same problem here. Every command that I tried in pip3 I got that message similar to yours. I reinstall and even that didn't work.

**Comment by kaandocal** [comment]
It appears that this is caused by the standard Python installation. Updating to Python 3.6 fixes the problem; alternatively the fix mentioned in the post can be used.

**Comment by slinderman** [comment]
Hi @kaandocal, thanks for following up on this.  Since it sounds like this is working on Python 3.6, I'm going to close this issue for now.
